language: 
  node_js
node_js:
  - '7.5.0'
env:
  - CXX=g++-4.8
sudo: 
  required
services:
  - docker
install: 
  - npm install -g newman
  - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.0.1-germanium
  
before_script:
  - chmod +x ./deploy.sh
script:
  ./deploy.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
